//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DingDing_Projector.Maxtrix_Control {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Maxtrix_Control.Maxtrix_ControlSoap")]
    public interface Maxtrix_ControlSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Maxtrix_Manage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DingDing_Projector.Maxtrix_Control.ReturnDataBase Maxtrix_Manage(DingDing_Projector.Maxtrix_Control.MaxtrixType maxtrixType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Maxtrix_Manage", ReplyAction="*")]
        System.Threading.Tasks.Task<DingDing_Projector.Maxtrix_Control.ReturnDataBase> Maxtrix_ManageAsync(DingDing_Projector.Maxtrix_Control.MaxtrixType maxtrixType);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MaxtrixType {
        
        /// <remarks/>
        maxtrix1,
        
        /// <remarks/>
        maxtrix2,
        
        /// <remarks/>
        maxtrix3,
        
        /// <remarks/>
        maxtrix4,
        
        /// <remarks/>
        maxtrix5,
        
        /// <remarks/>
        maxtrix6,
        
        /// <remarks/>
        maxtrix7,
        
        /// <remarks/>
        maxtrix8,
        
        /// <remarks/>
        maxtrix9,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnDataBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string methodField;
        
        private string innerErrorField;
        
        private string serverErrorField;
        
        private string return_ParamField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
                this.RaisePropertyChanged("Method");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InnerError {
            get {
                return this.innerErrorField;
            }
            set {
                this.innerErrorField = value;
                this.RaisePropertyChanged("InnerError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ServerError {
            get {
                return this.serverErrorField;
            }
            set {
                this.serverErrorField = value;
                this.RaisePropertyChanged("ServerError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Return_Param {
            get {
                return this.return_ParamField;
            }
            set {
                this.return_ParamField = value;
                this.RaisePropertyChanged("Return_Param");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Maxtrix_ControlSoapChannel : DingDing_Projector.Maxtrix_Control.Maxtrix_ControlSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Maxtrix_ControlSoapClient : System.ServiceModel.ClientBase<DingDing_Projector.Maxtrix_Control.Maxtrix_ControlSoap>, DingDing_Projector.Maxtrix_Control.Maxtrix_ControlSoap {
        
        public Maxtrix_ControlSoapClient() {
        }
        
        public Maxtrix_ControlSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Maxtrix_ControlSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Maxtrix_ControlSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Maxtrix_ControlSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DingDing_Projector.Maxtrix_Control.ReturnDataBase Maxtrix_Manage(DingDing_Projector.Maxtrix_Control.MaxtrixType maxtrixType) {
            return base.Channel.Maxtrix_Manage(maxtrixType);
        }
        
        public System.Threading.Tasks.Task<DingDing_Projector.Maxtrix_Control.ReturnDataBase> Maxtrix_ManageAsync(DingDing_Projector.Maxtrix_Control.MaxtrixType maxtrixType) {
            return base.Channel.Maxtrix_ManageAsync(maxtrixType);
        }
    }
}
